### ISSUE TITLE
Change of default occlusion template 

### ISSUE THREAD

**Issue by rubisco57** [supermemo/SuperMemoScripts#2]
Hi alexis,
I am really impressed by the image occlusion editor! It is accelerating the creation of occlusion items a lot. 
Thank you for sharing your work! 
I wondered if there is a way to change the default template of newly created occlusion items from the current one (with only an image component on it) to the template "Occlusion + 2 HTML". I tried to customize the OcclusionFormatComponentsAndRepHistory() function, but that did not do it... The last two components are not saved. Would you mind giving me a hand?

[OcclusionFormatComponentsAndRepHistory.txt](https://github.com/supermemo/SuperMemoScripts/files/2002262/OcclusionFormatComponentsAndRepHistory.txt)

**Comment by rubisco57** [comment]
[OcclusionFormatComponentsAndRepHistory.txt](https://github.com/supermemo/SuperMemoScripts/files/2002262/OcclusionFormatComponentsAndRepHistory.txt)

**Comment by alexis-** [comment]
Hi rubisco,

Thank you for the feedback, I am glad you find the editor useful !
What you describe seem to indicate an issue with the `ComponentNo` parameter, which should be set to the number of components in the Element, as illustrated here:
```
[...]
ComponentNo=4
Begin Component #1
[...]
```
(source: https://raw.githubusercontent.com/supermemo/ImageOcclusionEditor/master/Resources/Template_IIOTT.txt)

Let me know if that helps.

**Comment by rubisco57** [comment]
Thank you for getting back to me, alexis. 
I gave your suggestion a try with no luck - SuperMemo now throws an error: "Wrong component initialization sequence". 
The last component is currently no being created, i.e. if I change the order to "html, image, image, html" the last text box is left out.

**Comment by alexis-** [comment]
After testing with the code you previously uploaded, it appears to be working correctly for me.

I feel I may not have been very explicit about `ComponentNo`.
This property is already introduced somewhere else in the code, and set to a value of two.
Search for `out := RERElement(out, "ComponentNo", "2")` and replace 2 with 4.

**Comment by rubisco57** [comment]
Thank you. It works correctly for me as well. I should have studied the script closer... now that I deleted the attribute "ComponentNo" after the `LTrim` the error disappeared. 
I am curious about your plans for the driver that will replace the AutoHotkey script and might dare to write you again. Have a good one, alexis and thanks again.

**Comment by alexis-** [comment]
Feel free to write as you please, I'm always happy to be remembered these tools have a larger audience than just I.
*SuperMemo Assistant* has a much larger scope than the *SuperMemo Script* and the *Occlusion Editor*.
It is meant to implement some of the features that I and the community feel are missing from SuperMemo.
I am keeping both the surprise, and a reserve due to the technical constraints, a little longer as to what the features will be, but so far it is very promising !
