### ISSUE TITLE
Compatible with Supermemo 18?

### ISSUE THREAD

**Issue by ghost** [supermemo/SuperMemoScripts#3]
Hello.

I have AutoHotkey and the Image Occlusion Editor installed, and I downloaded the AHK script.   WheN I run the script press Ctrl Win O to open the editor the Windows On-Screen Keyboard launches and not the Image Occlusion Editor.   Am I doing something wrong?

**Comment by alexis-** [comment]
Hi @klingonunderwearmodel 

I have not used SM18 myself, but similar reports indicate the occlusion editor isn't compatible. There might be an upgrade sometime in the future, no ETA though.

**Comment by alexis-** [comment]
This plugin won't be updated to SM 18 and will be deprecated in favor of the new Image Occlusion plugin for SMA.
